// <auto-generated />
using System;
using Land_Readjustment_Tool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Land_Readjustment_Tool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401111528_updated_display_order")]
    partial class updated_display_order
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Canvas.CanvasLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FillColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("FillStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FillTransparency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HatchPattern")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrintable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelectable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelField")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelFontName")
                        .HasColumnType("TEXT");

                    b.Property<double>("LabelFontSize")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LayerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LineStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("LineWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PointSize")
                        .HasColumnType("REAL");

                    b.Property<string>("PointSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowLabels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFile")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tblCanvasLayers");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Canvas.CanvasObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BaselineParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BorderColorOverride")
                        .HasColumnType("TEXT");

                    b.Property<int>("CanvasLayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FillColorOverride")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FillTransparencyOverride")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LineStyleOverride")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LineWeightOverride")
                        .HasColumnType("REAL");

                    b.Property<string>("ObjectDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReplottedParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoadId")
                        .HasColumnType("INTEGER");

                    b.Property<Geometry>("Shape")
                        .IsRequired()
                        .HasColumnType("GEOMETRY");

                    b.Property<string>("SourceDxfHandle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanvasLayerId");

                    b.ToTable("tblCanvasObjects");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Contribution.ContributionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ApplicableAreaLimit")
                        .HasColumnType("REAL");

                    b.Property<string>("ApplicableAreaRule")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContributionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormulaType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeduction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rate")
                        .HasColumnType("REAL");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tblContributionCategories");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Contribution.ParcelContribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ApplicableAreaSqm")
                        .HasColumnType("REAL");

                    b.Property<int>("BaselineParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("ContributionAmountSqm")
                        .HasColumnType("REAL");

                    b.Property<int>("ContributionCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManualOverrideReason")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ManualOverrideValueSqm")
                        .HasColumnType("REAL");

                    b.Property<double>("RateApplied")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BaselineParcelId");

                    b.HasIndex("ContributionCategoryId");

                    b.ToTable("tblParcelContributions");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Contribution.ParcelContributionSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AreaDifferenceSqm")
                        .HasColumnType("REAL");

                    b.Property<int>("BaselineParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CashCompensationAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("EffectiveAreaSqm")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("FinalizedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCalculatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("NetReturnableAreaSqm")
                        .HasColumnType("REAL");

                    b.Property<double>("OriginalAreaSqm")
                        .HasColumnType("REAL");

                    b.Property<double?>("ReplottedAreaAssignedSqm")
                        .HasColumnType("REAL");

                    b.Property<int?>("ReplottedParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalContributionPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalContributionSqm")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalDeductionSqm")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalGeneralContributionSqm")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalSpecificContributionSqm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BaselineParcelId")
                        .IsUnique();

                    b.HasIndex("ReplottedParcelId");

                    b.ToTable("tblParcelContributionSummaries");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.CitizenshipConflict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CitizenshipNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportSessionId");

                    b.ToTable("tblCitizenshipConflicts");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.CitizenshipConflictRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CitizenshipConflictId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportedRawRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMarkedCorrect")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CitizenshipConflictId");

                    b.HasIndex("ImportedRawRecordId");

                    b.ToTable("tblCitizenshipConflictRecords");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.ImportSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReplaced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReplacedBySessionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRowsImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRowsInFile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRowsInvalid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("tblImportSessions");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.ImportedRawRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaBKD")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaRAPD")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AreaSqm")
                        .HasColumnType("REAL");

                    b.Property<string>("CitizenshipDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenshipDistrict")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenshipNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeduplicatedToOwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DeduplicationConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("DeduplicationMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherSpouseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsTenant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LandUse")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ManualReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapSheetNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MothNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipality")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaanaNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParcelNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawRowData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemporaryAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("WardNo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasManuallyReviewed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportSessionId");

                    b.ToTable("tblImportedRawRecords");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.ValidationError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportedRawRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportSessionId");

                    b.HasIndex("ImportedRawRecordId");

                    b.ToTable("tblValidationErrors");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.LandData.BaselineParcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CanvasObjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EffectiveAreaSqm")
                        .HasColumnType("REAL");

                    b.Property<string>("FullUniqueParcelCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasTenant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEffectiveAreaManual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LandOwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LandUse")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MalpotReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapSheetNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipality")
                        .HasColumnType("TEXT");

                    b.Property<double>("OriginalAreaSqm")
                        .HasColumnType("REAL");

                    b.Property<string>("ParcelNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WardNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanvasObjectId")
                        .IsUnique();

                    b.HasIndex("FullUniqueParcelCode")
                        .IsUnique();

                    b.HasIndex("ImportSessionId");

                    b.HasIndex("LandOwnerId");

                    b.HasIndex("MalpotReferenceId");

                    b.ToTable("tblBaselineParcels");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.LandData.LandOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CitizenshipIssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenshipIssueDistrict")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenshipNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentsFolderPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherOrSpouseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificationMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MatchConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("NeedsManualReview")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemporaryAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CitizenshipNumber")
                        .IsUnique()
                        .HasFilter("CitizenshipNumber IS NOT NULL");

                    b.ToTable("tblLandOwners");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.LandData.MalpotReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LandOwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MothNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaanaNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LandOwnerId", "MothNo")
                        .IsUnique();

                    b.ToTable("tblMalpotReferences");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.LandData.ParcelFrontage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaselineParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FacingDirection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("FrontageLength")
                        .HasColumnType("REAL");

                    b.Property<int?>("ReplottedParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaselineParcelId");

                    b.HasIndex("ReplottedParcelId");

                    b.HasIndex("RoadId");

                    b.ToTable("tblParcelFrontages");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Layout.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BlockArea")
                        .HasColumnType("REAL");

                    b.Property<string>("BlockCode")
                        .HasColumnType("TEXT");

                    b.Property<float>("BlockDepth")
                        .HasColumnType("REAL");

                    b.Property<string>("BlockLandUse")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CanvasObjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanvasObjectId")
                        .IsUnique();

                    b.ToTable("tblBlocks");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Layout.Road", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CanvasObjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RightOfWayWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("RoadCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoadName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoadStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoadType")
                        .HasColumnType("TEXT");

                    b.Property<double>("RoadWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("SurfaceType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanvasObjectId")
                        .IsUnique();

                    b.ToTable("tblRoads");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Project.ProjectInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsultingAgency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GazetteDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GazetteNotificationNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImplementingAgency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipality")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProjectEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectSite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProjectStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT");

                    b.Property<string>("WardNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tblProjectInfo", t =>
                        {
                            t.HasCheckConstraint("CK_ProjectInfo_SingleRow", "Id = 1");
                        });
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Project.ProjectSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanvasBackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanvasGridColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanvasGridVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoordinateSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DatumTransformationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultPaperSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultPrintScale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("MinPlotAreaSqm")
                        .HasColumnType("REAL");

                    b.Property<string>("ParcelNumberFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParcelNumberPadding")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParcelNumberPrefix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SnapEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SnapTolerancePx")
                        .HasColumnType("REAL");

                    b.Property<string>("TraditionalAreaUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoordinateSystemId");

                    b.HasIndex("DatumTransformationId");

                    b.ToTable("tblProjectSettings", t =>
                        {
                            t.HasCheckConstraint("CK_ProjectSettings_SingleRow", "Id = 1");
                        });
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Replotting.OriginalToReplottedMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaselineParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ContributedAreaSqm")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplottedParcelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaselineParcelId");

                    b.HasIndex("ReplottedParcelId");

                    b.ToTable("tblOriginalToReplottedMaps");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Replotting.PlotType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TypeCode")
                        .IsUnique();

                    b.ToTable("tblPlotTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Private ownership plot",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsSystemDefault = true,
                            TypeCode = "PRV",
                            TypeName = "Private"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Plot for sale to recover project costs",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsSystemDefault = true,
                            TypeCode = "SAL",
                            TypeName = "Sales Plot"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Government use plot",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsSystemDefault = true,
                            TypeCode = "GOV",
                            TypeName = "Government"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Parks and public open spaces",
                            DisplayOrder = 4,
                            IsActive = true,
                            IsSystemDefault = true,
                            TypeCode = "OPS",
                            TypeName = "Open Space"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Community use plot",
                            DisplayOrder = 5,
                            IsActive = true,
                            IsSystemDefault = true,
                            TypeCode = "COM",
                            TypeName = "Community"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Road right of way",
                            DisplayOrder = 6,
                            IsActive = true,
                            IsSystemDefault = true,
                            TypeCode = "ROD",
                            TypeName = "Road"
                        });
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Replotting.ReplottedParcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveNumberType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockSequenceNumber")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CanvasObjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DerivedNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double>("PlotAreaSqm")
                        .HasColumnType("REAL");

                    b.Property<int>("PlotTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemGeneratedNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("CanvasObjectId")
                        .IsUnique();

                    b.HasIndex("PlotTypeId");

                    b.ToTable("tblReplottedParcels");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Replotting.ReplottedParcelOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LandOwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OwnershipSharePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("ReplottedParcelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LandOwnerId");

                    b.HasIndex("ReplottedParcelId");

                    b.ToTable("tblReplottedParcelOwners");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Spatial.CoordinateSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpsgCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tblCoordinateSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "UTM44N",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "West Nepal. 78°E to 84°E. WGS84 datum.",
                            DisplayOrder = 1,
                            EpsgCode = 32644,
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "UTM Zone 44N — West Nepal",
                            ProjectionType = "TransverseMercator",
                            Region = "Nepal"
                        },
                        new
                        {
                            Id = 2,
                            Code = "UTM45N",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "East Nepal. 84°E to 90°E. WGS84 datum.",
                            DisplayOrder = 2,
                            EpsgCode = 32645,
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "UTM Zone 45N — East Nepal",
                            ProjectionType = "TransverseMercator",
                            Region = "Nepal"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MUTM81",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nepal Survey Dept. Central meridian 81°E. Everest 1830.",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "Modified UTM Zone 81 — Nepal",
                            ProjectionType = "TransverseMercator",
                            Region = "Nepal"
                        },
                        new
                        {
                            Id = 4,
                            Code = "MUTM84",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nepal Survey Dept. Central meridian 84°E. Everest 1830.",
                            DisplayOrder = 4,
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "Modified UTM Zone 84 — Nepal",
                            ProjectionType = "TransverseMercator",
                            Region = "Nepal"
                        },
                        new
                        {
                            Id = 5,
                            Code = "MUTM87",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nepal Survey Dept. Central meridian 87°E. Everest 1830.",
                            DisplayOrder = 5,
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "Modified UTM Zone 87 — Nepal",
                            ProjectionType = "TransverseMercator",
                            Region = "Nepal"
                        });
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Spatial.DatumTransformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicableCrsCodes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("DeltaX")
                        .HasColumnType("REAL");

                    b.Property<double>("DeltaY")
                        .HasColumnType("REAL");

                    b.Property<double>("DeltaZ")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<double>("RotationX")
                        .HasColumnType("REAL");

                    b.Property<double>("RotationY")
                        .HasColumnType("REAL");

                    b.Property<double>("RotationZ")
                        .HasColumnType("REAL");

                    b.Property<double>("ScalePpm")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tblDatumTransformations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicableCrsCodes = "MUTM81,MUTM82,MUTM83",
                            Code = "NAGARKOT_TM",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeltaX = 296.20699999999999,
                            DeltaY = 731.54499999999996,
                            DeltaZ = 273.00099999999998,
                            Description = "Based on Nagarkot GPS control points.",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "Nagarkot TM",
                            Region = "Nepal",
                            RotationX = 0.0,
                            RotationY = 0.0,
                            RotationZ = 0.0,
                            ScalePpm = 0.0,
                            Source = "Nagarkot TM",
                            SourceDatum = "Everest1830",
                            TargetDatum = "WGS84"
                        },
                        new
                        {
                            Id = 2,
                            ApplicableCrsCodes = "MUTM81,MUTM84,MUTM87",
                            Code = "KALIANPUR",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeltaX = 295.0,
                            DeltaY = 736.0,
                            DeltaZ = 257.0,
                            Description = "Traditional Kalianpur parameters. Used in older records.",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "Kalianpur Datum Parameters",
                            Region = "Nepal",
                            RotationX = 0.0,
                            RotationY = 0.0,
                            RotationZ = 0.0,
                            ScalePpm = 0.0,
                            Source = "Kalianpur datum parameters",
                            SourceDatum = "Everest1830",
                            TargetDatum = "WGS84"
                        },
                        new
                        {
                            Id = 3,
                            ApplicableCrsCodes = "MUTM81,MUTM84,MUTM87",
                            Code = "SURVEY_DEPT_7_PARAM",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeltaX = -124.3813,
                            DeltaY = 521.66999999999996,
                            DeltaZ = 764.51369999999997,
                            Description = "Official transformation. Recommended for all MUTM zones.",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "Nepal Survey Department (Official)",
                            Region = "Nepal",
                            RotationX = 17.148800000000001,
                            RotationY = -8.1153600000000008,
                            RotationZ = 11.184200000000001,
                            ScalePpm = -2.1105,
                            Source = "Survey Department Nepal",
                            SourceDatum = "Everest1830",
                            TargetDatum = "WGS84"
                        });
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Spatial.ProjectionParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CentralMeridian")
                        .HasColumnType("REAL");

                    b.Property<int>("CoordinateSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ellipsoid")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FalseEasting")
                        .HasColumnType("REAL");

                    b.Property<double?>("FalseNorthing")
                        .HasColumnType("REAL");

                    b.Property<double?>("InverseFlattening")
                        .HasColumnType("REAL");

                    b.Property<double?>("LatitudeOfOrigin")
                        .HasColumnType("REAL");

                    b.Property<double?>("ScaleFactor")
                        .HasColumnType("REAL");

                    b.Property<double?>("SemiMajorAxis")
                        .HasColumnType("REAL");

                    b.Property<string>("WktDefinition")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoordinateSystemId")
                        .IsUnique();

                    b.ToTable("tblProjectionParameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CentralMeridian = 81.0,
                            CoordinateSystemId = 3,
                            Ellipsoid = "Everest1830",
                            FalseEasting = 500000.0,
                            FalseNorthing = 0.0,
                            InverseFlattening = 300.80169999999998,
                            LatitudeOfOrigin = 0.0,
                            ScaleFactor = 0.99990000000000001,
                            SemiMajorAxis = 6377276.3449999997
                        },
                        new
                        {
                            Id = 2,
                            CentralMeridian = 84.0,
                            CoordinateSystemId = 4,
                            Ellipsoid = "Everest1830",
                            FalseEasting = 500000.0,
                            FalseNorthing = 0.0,
                            InverseFlattening = 300.80169999999998,
                            LatitudeOfOrigin = 0.0,
                            ScaleFactor = 0.99990000000000001,
                            SemiMajorAxis = 6377276.3449999997
                        },
                        new
                        {
                            Id = 3,
                            CentralMeridian = 87.0,
                            CoordinateSystemId = 5,
                            Ellipsoid = "Everest1830",
                            FalseEasting = 500000.0,
                            FalseNorthing = 0.0,
                            InverseFlattening = 300.80169999999998,
                            LatitudeOfOrigin = 0.0,
                            ScaleFactor = 0.99990000000000001,
                            SemiMajorAxis = 6377276.3449999997
                        });
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Canvas.CanvasObject", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Canvas.CanvasLayer", "CanvasLayer")
                        .WithMany("CanvasObjects")
                        .HasForeignKey("CanvasLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanvasLayer");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Contribution.ParcelContribution", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.LandData.BaselineParcel", "BaselineParcel")
                        .WithMany("ParcelContributions")
                        .HasForeignKey("BaselineParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Contribution.ContributionCategory", "ContributionCategory")
                        .WithMany("ParcelContributions")
                        .HasForeignKey("ContributionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaselineParcel");

                    b.Navigation("ContributionCategory");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Contribution.ParcelContributionSummary", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.LandData.BaselineParcel", "BaselineParcel")
                        .WithOne("ParcelContributionSummary")
                        .HasForeignKey("Land_Readjustment_Tool.Core.Entities.Contribution.ParcelContributionSummary", "BaselineParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Replotting.ReplottedParcel", "ReplottedParcel")
                        .WithMany("ParcelContributionSummaries")
                        .HasForeignKey("ReplottedParcelId");

                    b.Navigation("BaselineParcel");

                    b.Navigation("ReplottedParcel");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.CitizenshipConflict", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Import.ImportSession", "ImportSession")
                        .WithMany("CitizenshipConflicts")
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportSession");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.CitizenshipConflictRecord", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Import.CitizenshipConflict", "CitizenshipConflict")
                        .WithMany("ConflictingRecords")
                        .HasForeignKey("CitizenshipConflictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Import.ImportedRawRecord", "ImportedRawRecord")
                        .WithMany()
                        .HasForeignKey("ImportedRawRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CitizenshipConflict");

                    b.Navigation("ImportedRawRecord");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.ImportedRawRecord", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Import.ImportSession", "ImportSession")
                        .WithMany("ImportedRawRecords")
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportSession");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.ValidationError", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Import.ImportSession", "ImportSession")
                        .WithMany("ValidationErrors")
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Import.ImportedRawRecord", "ImportedRawRecord")
                        .WithMany("ValidationErrors")
                        .HasForeignKey("ImportedRawRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportSession");

                    b.Navigation("ImportedRawRecord");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.LandData.BaselineParcel", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Canvas.CanvasObject", "CanvasObject")
                        .WithOne("BaselineParcel")
                        .HasForeignKey("Land_Readjustment_Tool.Core.Entities.LandData.BaselineParcel", "CanvasObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Import.ImportSession", "ImportSession")
                        .WithMany()
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.LandData.LandOwner", "LandOwner")
                        .WithMany("BaselineParcels")
                        .HasForeignKey("LandOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.LandData.MalpotReference", "MalpotReference")
                        .WithMany("BaselineParcels")
                        .HasForeignKey("MalpotReferenceId");

                    b.Navigation("CanvasObject");

                    b.Navigation("ImportSession");

                    b.Navigation("LandOwner");

                    b.Navigation("MalpotReference");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.LandData.MalpotReference", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.LandData.LandOwner", "LandOwner")
                        .WithMany("MalpotReferences")
                        .HasForeignKey("LandOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandOwner");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.LandData.ParcelFrontage", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.LandData.BaselineParcel", "BaselineParcel")
                        .WithMany("ParcelFrontages")
                        .HasForeignKey("BaselineParcelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Replotting.ReplottedParcel", "ReplottedParcel")
                        .WithMany("ParcelFrontages")
                        .HasForeignKey("ReplottedParcelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Layout.Road", "Road")
                        .WithMany("ParcelFrontages")
                        .HasForeignKey("RoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaselineParcel");

                    b.Navigation("ReplottedParcel");

                    b.Navigation("Road");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Layout.Block", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Canvas.CanvasObject", "CanvasObject")
                        .WithOne("Block")
                        .HasForeignKey("Land_Readjustment_Tool.Core.Entities.Layout.Block", "CanvasObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanvasObject");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Layout.Road", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Canvas.CanvasObject", "CanvasObject")
                        .WithOne("Road")
                        .HasForeignKey("Land_Readjustment_Tool.Core.Entities.Layout.Road", "CanvasObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanvasObject");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Project.ProjectSettings", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Spatial.CoordinateSystem", "CoordinateSystem")
                        .WithMany()
                        .HasForeignKey("CoordinateSystemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Spatial.DatumTransformation", "DatumTransformation")
                        .WithMany()
                        .HasForeignKey("DatumTransformationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CoordinateSystem");

                    b.Navigation("DatumTransformation");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Replotting.OriginalToReplottedMap", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.LandData.BaselineParcel", "BaselineParcel")
                        .WithMany("OriginalToReplottedMaps")
                        .HasForeignKey("BaselineParcelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Replotting.ReplottedParcel", "ReplottedParcel")
                        .WithMany("OriginalToReplottedMaps")
                        .HasForeignKey("ReplottedParcelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaselineParcel");

                    b.Navigation("ReplottedParcel");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Replotting.ReplottedParcel", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Layout.Block", "Block")
                        .WithMany("ReplottedParcels")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Canvas.CanvasObject", "CanvasObject")
                        .WithOne("ReplottedParcel")
                        .HasForeignKey("Land_Readjustment_Tool.Core.Entities.Replotting.ReplottedParcel", "CanvasObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Replotting.PlotType", "PlotType")
                        .WithMany("ReplottedParcels")
                        .HasForeignKey("PlotTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("CanvasObject");

                    b.Navigation("PlotType");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Replotting.ReplottedParcelOwner", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.LandData.LandOwner", "LandOwner")
                        .WithMany("ReplottedParcelOwnerships")
                        .HasForeignKey("LandOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Replotting.ReplottedParcel", "ReplottedParcel")
                        .WithMany("ReplottedParcelOwners")
                        .HasForeignKey("ReplottedParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandOwner");

                    b.Navigation("ReplottedParcel");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Spatial.ProjectionParameters", b =>
                {
                    b.HasOne("Land_Readjustment_Tool.Core.Entities.Spatial.CoordinateSystem", "CoordinateSystem")
                        .WithOne("ProjectionParameters")
                        .HasForeignKey("Land_Readjustment_Tool.Core.Entities.Spatial.ProjectionParameters", "CoordinateSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoordinateSystem");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Canvas.CanvasLayer", b =>
                {
                    b.Navigation("CanvasObjects");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Canvas.CanvasObject", b =>
                {
                    b.Navigation("BaselineParcel");

                    b.Navigation("Block");

                    b.Navigation("ReplottedParcel");

                    b.Navigation("Road");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Contribution.ContributionCategory", b =>
                {
                    b.Navigation("ParcelContributions");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.CitizenshipConflict", b =>
                {
                    b.Navigation("ConflictingRecords");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.ImportSession", b =>
                {
                    b.Navigation("CitizenshipConflicts");

                    b.Navigation("ImportedRawRecords");

                    b.Navigation("ValidationErrors");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Import.ImportedRawRecord", b =>
                {
                    b.Navigation("ValidationErrors");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.LandData.BaselineParcel", b =>
                {
                    b.Navigation("OriginalToReplottedMaps");

                    b.Navigation("ParcelContributionSummary");

                    b.Navigation("ParcelContributions");

                    b.Navigation("ParcelFrontages");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.LandData.LandOwner", b =>
                {
                    b.Navigation("BaselineParcels");

                    b.Navigation("MalpotReferences");

                    b.Navigation("ReplottedParcelOwnerships");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.LandData.MalpotReference", b =>
                {
                    b.Navigation("BaselineParcels");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Layout.Block", b =>
                {
                    b.Navigation("ReplottedParcels");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Layout.Road", b =>
                {
                    b.Navigation("ParcelFrontages");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Replotting.PlotType", b =>
                {
                    b.Navigation("ReplottedParcels");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Replotting.ReplottedParcel", b =>
                {
                    b.Navigation("OriginalToReplottedMaps");

                    b.Navigation("ParcelContributionSummaries");

                    b.Navigation("ParcelFrontages");

                    b.Navigation("ReplottedParcelOwners");
                });

            modelBuilder.Entity("Land_Readjustment_Tool.Core.Entities.Spatial.CoordinateSystem", b =>
                {
                    b.Navigation("ProjectionParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
