// <auto-generated />
using Land_Readjustment_Tool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Land_Readjustment_Tool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513100000_AddLayerLabelScalingBehavior")]
    partial class AddLayerLabelScalingBehavior
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");
#pragma warning restore 612, 618
        }
    }
}
